development: &development
  papers:
    com_myrepublica:
      class_name: ComMyrepublica
      enabled: true
    com_nagariknews:
      class_name: ComNagariknews
      enabled: true
    com_thehimalayantimes:
      class_name: ComThehimalayantimes
      enabled: true
    com_ekantipur:
      class_name: ComEkantipur
      enabled: true
    com_ekantipur_kpost:
      class_name: ComEkantipurKpost
      enabled: true
    xyz:
      class_name: Dummy
      enabled: false

  pdf_write_dir: lib/webapp/public/pdf
  thumbnail_write_dir: lib/webapp/public/thumbnail
  tmp_dir: tmp


test: 
  <<: *development
  pdf_write_dir: tmp/pdf_out_test
  thumbnail_write_dir: tmp/thumbnail_out_test

production: 
  <<: *development
  static_dir: /data/bharkharapp/public
  pdf_write_dir: /data/bharkharapp/public/pdf
  thumbnail_write_dir: /data/bharkharapp/public/thumbnail
